// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
export default {
  login: 'MuneebSamar',
  id: 99045014,
  node_id: 'U_kgDOBedOlg',
  avatar_url: 'https://avatars.githubusercontent.com/u/99045014?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/MuneebSamar',
  html_url: 'https://github.com/MuneebSamar',
  followers_url: 'https://api.github.com/users/MuneebSamar/followers',
  following_url:
    'https://api.github.com/users/MuneebSamar/following{/other_user}',
  gists_url: 'https://api.github.com/users/MuneebSamar/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/MuneebSamar/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/MuneebSamar/subscriptions',
  organizations_url: 'https://api.github.com/users/MuneebSamar/orgs',
  repos_url: 'https://api.github.com/users/MuneebSamar/repos',
  events_url: 'https://api.github.com/users/MuneebSamar/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/MuneebSamar/received_events',
  type: 'User',
  site_admin: false,
  name: 'Muneeb Ur Rehman',
  company: 'appifytech',
  blog: 'woodmix.pk/woodmix.html',
  location: 'Lahore',
  email: null,
  hireable: null,
  bio: 'Front-End-Developer',
  twitter_username: 'MuneebU51273026',
  public_repos: 2,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2022-02-04T18:54:56Z',
  updated_at: '2022-10-06T12:56:13Z',
}
